// AutolinkedNativeModules.g.cs contents generated by "react-native autolink-windows"

using System.Collections.Generic;

// Namespaces from react-native-native-module-c-sharp
using ReactNativeNativeModuleCSharp;

namespace Microsoft.ReactNative.Managed
{
    internal static class AutolinkedNativeModules
    {
        internal static void RegisterAutolinkedNativeModulePackages(IList<IReactPackageProvider> packageProviders)
        { 
            // IReactPackageProviders from react-native-native-module-c-sharp
            packageProviders.Add(new ReactNativeNativeModuleCSharp.ReactPackageProvider());
        }
    }
}
